# Generated by Django 6.0.6 on 2026-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(default=9876543210, max_length=15),
            preserve_default=False,
        ),
    ]
